# Generated by Django - add pdf_file to Certificate
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_certificate_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/generated/'),
        ),
    ]
