# Generated by Django 4.2.27 on 2025-12-25 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_certificate_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
