# Generated by Django 4.2.27 on 2025-12-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_add_pdf_file'),
        ('lms', '0005_certificate_certificate_id'),
    ]

    operations = [
    ]
